== https://adventofcode.com/2017/day/9[Stream Processing]

This is my very first attempt to write a https://www.rust-lang.org[Rust program], so I'm gonna add all the steps necessary.

=== Learning

Rust comes with a great https://www.rust-lang.org/learn[book].

=== Installation

I trusted the site and ran the installation directly from the web:

[source,console]
----
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
----

That brings you the Rust compiler and Cargo, a tool for managing projects, pretty much like Maven or Gradle for Java.
It creates a project for like this:

[source,console]
----
cargo new stream-processing
----

=== The program itself

Nothing to fancy here.
I thought briefly about using https://pest.rs[Pest], 
because it's what I saw a colleague using and which got me into this.
But that's overkill for the task at hand.
I basically looked at the chars and implemented the algorithm described straight away.

[source,rust,numbered,indent=0]
----
include::src/lib.rs[tags=readingTheInput]
----

=== Compiling and running

The out of the box experience with Cargo is quite pleasant:

[source,console]
----
cargo test # <>
cargo build # <>
cargo build --release # <>
----
<> Execute all tests annotated with `#[test]` inside the `#[cfg(test)]` test configuration
<> Build debug image
<> Or build an optimized image

A `stream-processing` binary will be created in `target/debug` or in `target/release`.
It can be run directly.

As an alternative, you run the program via Cargo itself:

[source,console]
----
cargo run input.txt 
----


NOTE: Tested with `cargo 1.41.0 (626f0f40e 2019-12-03)` and `rustc 1.41.0 (5e1a79984 2020-01-27)`
      Correct solutions are: `14190` and `7053`
