:tags: CTE

== https://adventofcode.com/2019/day/1[The Tyranny of the Rocket Equation] - The database strikes back

This one is a solution just for fun. 
Why not solving the thing with SQL?

I did this with PostgreSQL, which supports https://www.postgresql.org/docs/11/queries-with.html[recursive common table expressions].

First, change into the directory of this solution, bring up a Docker container running the latest PostgreSQL version, copy the `input.txt` into it, create an `aoc` database and finally login:

[source,console]
----
docker run -d -p 5432:5432  --name postgres1 postgres:12.1
docker cp input.txt postgres1:/tmp/
docker exec -it postgres1 createdb -U postgres aoc # <1>
docker exec -it postgres1 psql -U postgres aoc
----
<1> Create a `aoc` database

First, create a table and load the data:

[source,sql]
----
include::prepare.sql[]
----

First star is trivial:

[source,sql]
----
include::star1.sql[]
----

Second star is fun:

[source,sql]
----
include::star2.sql[]
----
<1> Declare a recursive common table expression
<2> Define the initial value
<3> Recursively select from `fuel_for_fuel`. The nested from clause is only needed to avoid having the equation thrice.

Because? It's fun.

NOTE: Tested with `postgres:12.1`
      Correct solutions are: `3511949` and `5265045`.
